# Run ESlint
name: ESlint
on: pull_request
jobs:
  suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint
